import {
  LayoutDashboard, Package, FileText,
  BarChart3, BookOpen, GraduationCap,
  Building2, FolderOpen, Bell, Users,
  Shield, Key, ClipboardList, Settings
} from 'lucide-react'

export const MENU_SECTIONS = {
  main: { label: null },
  admin: { label: 'Administration' },
}

export const NAV_ITEMS = [
  {
    id: 'dashboard',
    to: '/dashboard',
    icon: LayoutDashboard,
    label: 'Tableau de bord',
    section: null,
    permission: null,
    roles: null,
    badge: null,
  },
  {
    id: 'operateurs',
    to: '/operateurs',
    icon: Building2,
    label: 'Opérateurs',
    section: null,
    permission: 'operateurs.view_operateur',
    roles: null,
    badge: null,
  },
  {
    id: 'tracabilite',
    to: '/tracabilite',
    icon: Package,
    label: 'Traçabilité',
    section: null,
    permission: 'traceability.view_traceability',
    roles: null,
    badge: null,
  },
  {
    id: 'documents',
    to: '/documents',
    icon: FileText,
    label: 'Documents',
    section: null,
    permission: 'archive.view_document',
    roles: null,
    badge: null,
  },
  {
    id: 'stats',
    to: '/stats',
    icon: BarChart3,
    label: 'Statistiques',
    section: null,
    permission: null,
    roles: null,
    badge: null,
  },
  {
    id: 'nomenclature',
    to: '/nomenclature',
    icon: BookOpen,
    label: 'Nomenclature',
    section: null,
    permission: null,
    roles: null,
    badge: null,
  },
  {
    id: 'glossaire',
    to: '/glossaire',
    icon: GraduationCap,
    label: 'Glossaire',
    section: null,
    permission: null,
    roles: null,
    badge: null,
  },
  {
    id: 'archive',
    to: '/archive',
    icon: FolderOpen,
    label: 'Archive',
    section: null,
    permission: 'archive.view_document',
    roles: null,
    badge: null,
  },
  {
    id: 'alertes',
    to: '/alertes',
    icon: Bell,
    label: 'Alertes',
    section: null,
    permission: null,
    roles: null,
    badge: null,
  },
  {
    id: 'admin-users',
    to: '/administration/users',
    icon: Users,
    label: 'Utilisateurs',
    section: 'admin',
    permission: null,
    roles: ['SUPERADMIN', 'ADMIN'],
    badge: null,
  },
  {
    id: 'admin-roles',
    to: '/administration/roles',
    icon: Shield,
    label: 'Rôles',
    section: 'admin',
    permission: null,
    roles: ['SUPERADMIN', 'ADMIN'],
    badge: null,
  },
  {
    id: 'admin-permissions',
    to: '/administration/permissions',
    icon: Key,
    label: 'Permissions',
    section: 'admin',
    permission: null,
    roles: ['SUPERADMIN', 'ADMIN'],
    badge: null,
  },
  {
    id: 'admin-audit',
    to: '/administration/audit-logs',
    icon: ClipboardList,
    label: 'Journal d\'audit',
    section: 'admin',
    permission: null,
    roles: ['SUPERADMIN', 'ADMIN'],
    badge: null,
  },
  {
    id: 'admin-settings',
    to: '/administration/settings',
    icon: Settings,
    label: 'Paramètres',
    section: 'admin',
    permission: null,
    roles: ['SUPERADMIN', 'ADMIN'],
    badge: null,
  },
]

export const BOTTOM_ITEMS = [
  {
    id: 'profil',
    to: '/profil',
    icon: null,
    label: 'Mon Profil',
    permission: null,
    roles: null,
  },
  {
    id: 'logout',
    to: null,
    icon: null,
    label: 'Déconnexion',
    permission: null,
    roles: null,
  },
]
